### ISSUE TITLE
Gear Ratio "???"

### ISSUE THREAD

**Issue by IRIX64** [Bornhall/gt7telemetry#3]
Hello,
i took notice that in the list of the gear ratio the last one is named "???" and i assume that should be the Reverse Gear which is missing right now on the list. 

Thank you for your work and the script. Runs fine on my Windows 11.

Regards,
Joerg

**Comment by Bornhall** [comment]
Sorry for the delay in responding here... This project is more or less "abandoned" as it is, but can be of use for others to start off with or build upon.

However, the gear ratio that you refer to (I think) was later dubbed as "corresponds to the Top Speed setting of a customizable gear box in the car settings, given as gear ratio" in the thread on GTPlanet: https://www.gtplanet.net/forum/threads/gt7-is-compatible-with-motion-rig.410728/page-4

So that's basically it. As it is, I am focusing on the iOS app EzioDash I have developed.
